<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>arm_bringup</name>
  <version>0.0.0</version>
  <description>Gazebo 스폰, 컨트롤러, MoveIt 실행을 위한 launch 와 설정</description>
  <maintainer email="52230596+hwjeon0123@users.noreply.github.com">hwjeon</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>arm_description</depend>
  <depend>robot_state_publisher</depend>
  <depend>ros_gz_sim</depend>
  <depend>xacro</depend>
  <depend>moveit_configs_utils</depend>
  <depend>ament_index_python</depend>
  <depend>moveit_ros_move_group</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
